export const CHANGE_MOVING = "CHANGE_MOVING";
export const CHANGE_ENV = "CHANGE_ENV";
export const SET_PLAYER_CENTER = "SET_PLAYER_CENTER";
export const SET_BACKWORLD = "SET_BACKWORLD_BTN"
export const SET_PLAYER_INVERT = "SET_PLAYER_INVERT";